version: 0.0
os: windows
files:
  - source: /
    destination: C:\MyCicdApplication

hooks:
  BeforeInstall:
    - location: scripts\install-dotnet-core.ps1
      timeout: 300
      runas: Administrator

  AfterInstall:
    - location: scripts\start-service.ps1
      timeout: 300
      runas: Administrator
