version: 0.0
os: windows
files:
  - source: C:\MyCicdApplication\AwsConsolerepo\PipelineTesting
    destination: /var/www/html/
hooks:
  ApplicationStart:
    - location: scripts/before-install.bat
      timeout: 300
      runas: Administrator
